language: java
sudo: false
script:
  - if [[ "$TRAVIS_PULL_REQUEST" != false ]]; then sbt -Dakka.test.timefactor=2 'set concurrentRestrictions in Global += Tags.limit(Tags.Test, 1)' test; else travis_retry sbt -Dakka.test.timefactor=2 'set concurrentRestrictions in Global += Tags.limit(Tags.Test, 1)' test; fi
branches:
  only:
    - master
jdk:
  - oraclejdk8
notifications:
  slack: buttercoin:RVh8tWlAPCmdIEdtgXRXCWYS
